### PR TITLE
[ MOSIP-20594 ] Added resident-app helm/chart for v3

### PR DESCRIPTION
**Pull request by syed-salman-technoforte**

### CODE REVIEW

**Review by ckm007 — COMMENTED** [review]
what is the need of notes,txt there?

**Comment by syed-salman-technoforte** [comment]
> what is the need of notes,txt there? also please add proper jira id and message for PR

To print out a block of helpful information for users. you can also refer [here](https://helm.sh/docs/chart_template_guide/notes_files/)

**Review by ckm007 — COMMENTED** [review]
do we need this
charts/resident-app/templates/NOTES.txt
?
also lets move the image to mosipqa and then use it here.

**Comment by syed-salman-technoforte** [comment]
do we need this charts/resident-app/templates/NOTES.txt ?
===> It is there in all other charts
also, let's move the image to mosipqa and then use it here.
===> yes.. transferred image from mosipdev/mimoto:develop to mosipqa/mimoto:develop

**Pull request merged**
